kafka:
  brokers: localhost:9092,localhost:9093,localhost:9094
  offset:
    topic: "__consumer_offsets"
    partitions: 50
    reset: true
  healthcheck:
    topic: "health"

zookeeper:
  uris: localhost:2181

jmx:
  kafka:
    jmxurl: localhost:19999,localhost:29999,localhost:39999
  zookeeper:
    jmxurl: localhost:49999
  filterTemplate: JMXFilterTemplate

server:
  port: 8121
  context-path: /
  debug: true
  security:
    check: true
    checkInitDelay: 30
    checkSecurityInterval: 5

spring:
  kafka:
    bootstrap-servers: ${kafka.brokers}
    consumer:
      group-id: "kafka-zk-rest"
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: detect
  aop:
    auto: true

